// Zero sample records initial mock data structure
export const initialMockData = {
  users: [
    { id: 1, username: "hr_manager", email: "hr@lankaworkforce.com", fullName: "HR Manager", role: "HR_MANAGER", active: true },
    { id: 2, username: "ops_manager", email: "ops@lankaworkforce.com", fullName: "Operations Manager", role: "OPERATIONS_MANAGER", active: true },
    { id: 3, username: "senior_admin", email: "admin@lankaworkforce.com", fullName: "Senior Admin", role: "SENIOR_ADMIN", active: true },
    { id: 4, username: "finance_exec", email: "finance@lankaworkforce.com", fullName: "Finance Executive", role: "FINANCE_EXECUTIVE", active: true },
    { id: 5, username: "employee_user", email: "emp@lankaworkforce.com", fullName: "Staff Member", role: "EMPLOYEE", active: true },
    { id: 6, username: "it_coordinator", email: "it@lankaworkforce.com", fullName: "IT Coordinator", role: "IT_COORDINATOR", active: true },
  ],

  departments: [],
  positions: [],
  employees: [],
  vacancies: [],
  workLocations: [],
  shifts: [],
  assignments: [],
  workforcePlans: [],
  transfers: [],
  replacements: [],
  meetings: [],
  recalls: [],
  attendances: [],
  leaves: [],
  overtime: [],
  timesheets: [],
  benefits: [],
  payrolls: [],
  payslips: [],
  policies: [],
  acknowledgements: [],
  warnings: [],
  disciplinary: [],
  kpis: [],
  evaluations: [],
  supervisorFeedbacks: [],
  goals: [],
  tickets: [],
  backups: [],
  auditLogs: [],
  notifications: []
};
